"""empty message

Revision ID: 057bfeb336d6
Revises: 
Create Date: 2020-06-15 10:34:13.515600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '057bfeb336d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenu', sa.Column('name_en', sa.String(length=50), nullable=False))
    op.add_column('submenu', sa.Column('name_zh', sa.String(length=50), nullable=False))
    op.drop_column('submenu', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenu', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('submenu', 'name_zh')
    op.drop_column('submenu', 'name_en')
    # ### end Alembic commands ###
