"""empty message

Revision ID: 1d689de00b99
Revises: 057bfeb336d6
Create Date: 2021-07-20 14:45:01.926000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d689de00b99'
down_revision = '057bfeb336d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('from_name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'from_name')
    # ### end Alembic commands ###
