"""empty message

Revision ID: 3643e58c443b
Revises: 6eacbdef798c
Create Date: 2021-07-27 14:43:47.780000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3643e58c443b'
down_revision = '6eacbdef798c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reply', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply', type_='foreignkey')
    # ### end Alembic commands ###
