"""empty message

Revision ID: 6eacbdef798c
Revises: 1957b8814a5a
Create Date: 2021-07-27 14:19:04.324000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eacbdef798c'
down_revision = '1957b8814a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reply_ibfk_1', 'reply', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('reply_ibfk_1', 'reply', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###
