"""empty message

Revision ID: 9e30ef3cbb28
Revises: 
Create Date: 2021-09-11 10:21:57.239914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e30ef3cbb28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('likes', sa.Integer(), nullable=False))
    op.add_column('article', sa.Column('stars', sa.Integer(), nullable=False))
    op.add_column('article', sa.Column('views', sa.Integer(), nullable=False))
    op.add_column('comment', sa.Column('likes', sa.Integer(), nullable=False))
    op.add_column('reply', sa.Column('likes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reply', 'likes')
    op.drop_column('comment', 'likes')
    op.drop_column('article', 'views')
    op.drop_column('article', 'stars')
    op.drop_column('article', 'likes')
    # ### end Alembic commands ###
