"""empty message

Revision ID: f8578b3c6404
Revises: 1d689de00b99
Create Date: 2021-07-20 14:47:19.063000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8578b3c6404'
down_revision = '1d689de00b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('from_name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reply', 'from_name')
    # ### end Alembic commands ###
